### create new support ticket

POST http://localhost:3000/support
Content-Type: application/json

{
    "question": "Where can I contact support for password reset?",
    "answer": "You can contact our support team for password reset by emailing",
    "topic": "Account Management"
}